### ISSUE TITLE
EvilCraft-Compat error?

### ISSUE THREAD

**Issue by Darkslayer99-beep** [rubensworks/EvilCraft#1139]
#### Issue type:

- [x] Bug 

____

#### Title:

**[1.12.2] CRASH: `NoSuchMethodError` with EvilCraft-Compat and recent EnderIO versions.**

#### Details:

**Description of the issue:**

The game is crashing on startup during the mod initialization phase when running **EvilCraft-Compat** alongside modern versions of EnderIO for Minecraft 1.12.2.

The crash occurs specifically within the EvilCraft-Compat module's code for integrating with EnderIO's recipe system, indicating a version incompatibility where the compatibility module is attempting to call an EnderIO method that no longer exists in recent EnderIO builds.

**Affected Versions:**

Minecraft Version: 1.12.2
Forge Version: 14.23.5.2860
EvilCraft Version:Your EvilCraft version number,  0.10.78
EnderIO Version: The specific EnderIO version that is causing the crash, e.g., 5.2.64
Working EnderIO Version (if known): The previous version of EnderIO that did not crash the game, e.g., 5.2.61

**Critical Error Snippet:**

```java
Caused by: java.lang.NoSuchMethodError: crazypants.enderio.base.recipe.Recipe.<init>(Lcrazypants/enderio/base/recipe/IRecipeInput;ILcrazypants/enderio/base/recipe/RecipeBonusType;[Lcrazypants/enderio/base/recipe/RecipeOutput;)V
    at org.cyclops.evilcraftcompat.modcompat.enderio.EnderIORecipeManager.register(EnderIORecipeManager.java:28)

I Understand if 1.12.2 is no longer worked on, then thank for your time.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
Our dev is indeed not working on 1.12 anymore. The oldest version on long term support is 1.19.2.
But you're welcome to discuss this or any 1.12 issue you may be encountering on our discord, where others may be able to help figure out what is happening, or even talk to our experts, one of which is still trying to get 1.12 to work.

**Comment by rubensworks** [comment]
See workaround in https://github.com/CyclopsMC/EvilCraft/issues/807
